#!/bin/sh
# $Id: elisp-comp,v 1.2 1998/03/24 18:05:49 law Exp $
# Trivial script to compile the Elisp files.
setpath=${TMPDIR-/tmp}/elc.$$
echo "(setq load-path (cons nil load-path))" > $setpath
emacs -batch -l $setpath -f batch-byte-compile "$@"
rm -f $setpath
